# Generated by Django 4.2.2 on 2023-06-13 08:49

import BadjosSmokeBBQ.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('bbq_dish', 'BBQ Dish'), ('side', 'Side'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=8)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='food_photos/', validators=[BadjosSmokeBBQ.core.validators.validate_file_less_than_7mb])),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
