# Generated by Django 4.2.2 on 2023-06-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_email',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
