# Generated by Django 4.2.2 on 2023-07-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=200),
        ),
    ]
