# Generated by Django 4.2.2 on 2023-06-13 08:49

import BadjosSmokeBBQ.core.model_mixins
import BadjosSmokeBBQ.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='football_photos/', validators=[BadjosSmokeBBQ.core.validators.validate_file_less_than_7mb])),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('street_life', 'Street Life'), ('kitchen_life', 'Kitchen Life'), ('events', 'Events'), ('foods', 'Foods')], max_length=12)),
            ],
            bases=(BadjosSmokeBBQ.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
