# Generated by Django 4.2.2 on 2023-06-15 08:46

import BadjosSmokeBBQ.core.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[BadjosSmokeBBQ.core.validators.validate_file_less_than_7mb]),
        ),
    ]
