# Generated by Django 4.2.2 on 2023-06-13 08:49

import BadjosSmokeBBQ.core.model_mixins
import BadjosSmokeBBQ.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('photo', models.ImageField(blank=True, upload_to='articles_photos/', validators=[BadjosSmokeBBQ.core.validators.validate_file_less_than_7mb])),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('beverages', 'Beverages'), ('experiments', 'Experiments'), ('events', 'Events'), ('internal', 'Internal'), ('the_rest', 'The Rest')], max_length=11)),
                ('publication_date', models.DateField(auto_now=True)),
            ],
            bases=(BadjosSmokeBBQ.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='articles.article')),
            ],
        ),
    ]
