# Generated by Django 4.2.2 on 2023-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='commentor_email',
            field=models.EmailField(default='n', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='commentor_name',
            field=models.CharField(default='name', max_length=60),
            preserve_default=False,
        ),
    ]
