# Generated by Django 4.2.2 on 2023-07-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlecomment_commentor_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
