# Generated by Django 4.2.2 on 2023-06-13 08:49

import BadjosSmokeBBQ.core.model_mixins
import BadjosSmokeBBQ.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('photo', models.ImageField(blank=True, upload_to='events-photos/', validators=[BadjosSmokeBBQ.core.validators.validate_file_less_than_7mb])),
                ('venue_date', models.DateField(blank=True)),
                ('location', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            bases=(BadjosSmokeBBQ.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
